services:
  db_my_money:
    image: postgres
    container_name: db_my_money
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./back-end/.env.docker
    volumes:
      - pg:/var/lib/postgresql/data

  node_app_my_money:
    container_name: node_app_my_money
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_my_money
    env_file:
      - ./back-end/.env.docker

  react_app_my_money:
    build: ./front-end
    container_name: react_app_my_money
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db_my_money
      - node_app_my_money
      - react_app_my_money

volumes:
  pg:
  build_react: