name: Pull Request
on: [pull_request]
jobs: 
  PullRequest: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USERNAME: "postgres"
          envkey_POSTGRES_PASSWORD: "SuperSecurePasswordForTestsOnly"
          envkey_POSTGRES_DB: "my_money_test"
          envkey_DATABASE_URL: "postgres://postgres:SuperSecurePasswordForTestsOnly@db_my_money:5432/my_money_test"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node_app_my_money npm run test:integration

